version: "2.2"

services:
  mysql-db:
    image: mysql
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'login'
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
     - 8081:80
  webapp:
    image: java-login
    restart: always
    container_name: java-login
    environment: 
     MYSQL_HOST: 'mysql-db'
     MYSQL_USER: "root"
     MYSQL_PASSWORD: "password"
     MYSQL_DATABASE: "login"
    ports:
    - 8080:8080
    depends_on:
    - mysql-db
  nginx-proxy:
    image: nginx
    container_name: "nginx_proxy"
    ports:
    - 8082:80
    volumes:
     - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
    - webapp
  
      
  